namespace: tenant-3

department-chart:
  name: backend
  namespace: tenant-3
  image:
    repository: ghcr.io/msauhammel/department-service
    tag: "v0.1.1"
  service:
    port: 3002
    nodePort: 30002

employee-frontend-chart:
  fullnameOverride: frontend
  namespace: tenant-3
  image:
    repository: ghcr.io/msauhammel/employee-frontend
    tag: "v0.1.1"
  service:
    port: 3000
    nodePort: 30000
  containerPort: 3000
