# API version of the ArgoCD Application resource
apiVersion: argoproj.io/v1alpha1
# Kind of the resource, here it is an Application for ArgoCD
kind: Application
metadata:
  # Name of the ArgoCD Application
  name: podtato-head
  # Namespace where the ArgoCD Application is deployed
  namespace: argocd
spec:
  # Project under which this application is categorized
  project: default
  source:
    # Git repository URL containing the application manifests or Helm chart
    repoURL: https://github.com/podtato-head/podtato-head-app.git
    # Git revision (branch, tag, or commit) to be deployed
    targetRevision: v0.3.0
    # Path within the repository where the chart or manifests are located
    path: chart
  destination:
    # Kubernetes API server address where the app will be deployed
    server: https://kubernetes.default.svc
    # Namespace in the cluster where resources will be created
    namespace: podtato-helm
  syncPolicy:
    automated:
      # Automatically sync and apply changes from the source repo
      selfHeal: true
      # Automatically delete resources that are no longer defined in the source
      prune: true
    # Additional options for synchronization behavior
    syncOptions:
      # Automatically create the destination namespace if it does not exist
      - CreateNamespace=true