namespace: employeeapp

department-chart:
  name: backend
  namespace: employeeapp
  image:
    repository: ghcr.io/msauhammel/department-service
    tag: "v0.1.1"
  service:
    port: 3002
    nodePort: 30002

employee-frontend-chart:
  fullnameOverride: frontend
  namespace: employeeapp
  image:
    repository: ghcr.io/msauhammel/employee-frontend
    tag: "v0.1.1"
  service:
    port: 3000 # This is the service's port (what the Ingress connects to)
    nodePort: 30000
  containerPort: 3000 # <-- ADDED: This is the port your frontend application listens on inside its container