name: tofu Plan & Apply  # Name of the workflow

 # Trigger the workflow on pull requests and pushes to the main branch
on:
  # pull_request:              # Trigger on PRs targeting main
  #   branches: [ main ]
  push:                      # Trigger on commits pushed to main
    branches: [ main ]

defaults:
  run:
    working-directory: ./terraform

 # Define the job for tofu operations
jobs:
  tofu:                 # Define a job called 'tofu'
    runs-on: ubuntu-latest   # Use latest Ubuntu runner

    # Set environment variables required for Exoscale access
    env:                     # Define environment variables from GitHub secrets
      TF_VAR_exoscale_key: ${{ secrets.EXOSCALE_KEY }}
      TF_VAR_exoscale_secret: ${{ secrets.EXOSCALE_SECRET }}
      TF_VAR_cluster_name: "employee-sks-cluster"
      TF_VAR_PG_ADMIN: ${{ secrets.PG_ADMIN }}
      TF_VAR_PG_PASSWORD: ${{ secrets.PG_PASSWORD }}

    # List of steps to set up tools, validate cluster access, and run tofu plans and applies
    steps:
      - name: Checkout repository  # Step 1: Checkout code
        uses: actions/checkout@v4

      # Install the specified version of OpenTofu CLI
      - name: Install OpenTofu     # Step 2: Install OpenTofu CLI
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      # Initialize tofu
      - name: Tofu init
        run: |
         cd cluster
         tofu init
         
         cd ../db
         tofu init
         
         cd ../workloads
         tofu init
         
         cd ../rootapp
         tofu init

      # Automatically apply tofu changes when code is pushed to main
      - name: Run OpenTofu Apply        # Step 6: Auto apply on push to main
        run: |
         cd cluster
         tofu plan
         tofu apply -auto-approve
         
         cd ../db
         tofu plan
         tofu apply -auto-approve
         
         cd ../workloads
         tofu plan
         tofu apply -auto-approve
         
         cd ../rootapp
         tofu plan
         tofu apply -auto-approve
      
      # Automatically apply tofu changes when code is pushed to main
      # - name: Run OpenTofu Apply        # Step 6: Auto apply on push to main
      #  run: sh apply.sh
